version: "2"

services:
    alfresco:
        image: quay.io/alfresco/alfresco-content-repository:7.1.0.1
        mem_limit: 1700m
        environment:
            JAVA_TOOL_OPTIONS: "
                -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
                "
            JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=127.0.0.1
                -Dshare.port=8080
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dtransform.service.enabled=true
                -Dtransform.service.url=http://transform-router-proxy
                -Dsfs.url=http://shared-file-store-proxy/
                -DlocalTransform.core-aio.url=http://transform-core-aio-proxy/
                -Dcsrf.filter.enabled=false
                -Ddsync.service.uris=http://localhost:9090/alfresco
                -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
                "

    transform-router-1:
        mem_limit: 512m
        image: quay.io/alfresco/alfresco-transform-router:1.4.1
        environment:
          JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
          ACTIVEMQ_URL: "nio://activemq:61616"
          CORE_AIO_URL : "http://transform-core-aio-proxy"
          FILE_STORE_URL: "http://shared-file-store-proxy/alfresco/api/-default-/private/sfs/versions/1/file"
        links:
            - activemq

    transform-router-2:
        mem_limit: 512m
        image: quay.io/alfresco/alfresco-transform-router:1.4.1
        environment:
          JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
          ACTIVEMQ_URL: "nio://activemq:61616"
          CORE_AIO_URL : "http://transform-core-aio-proxy"
          FILE_STORE_URL: "http://shared-file-store-proxy/alfresco/api/-default-/private/sfs/versions/1/file"
        links:
            - activemq

    transform-router-proxy:
        image: nginx:stable-alpine
        depends_on:
            - transform-router-1
            - transform-router-2
        volumes:
            - ./config/nginx-router.conf:/etc/nginx/nginx.conf

    transform-core-aio-1:
        image: alfresco/alfresco-transform-core-aio:2.5.3
        mem_limit: 1536m
        environment:
            JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store-proxy/alfresco/api/-default-/private/sfs/versions/1/file"
        links:
            - activemq

    transform-core-aio-2:
        image: alfresco/alfresco-transform-core-aio:2.5.3
        mem_limit: 1536m
        environment:
            JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store-proxy/alfresco/api/-default-/private/sfs/versions/1/file"
        links:
            - activemq

    transform-core-aio-proxy:
        image: nginx:stable-alpine
        depends_on:
            - transform-core-aio-1
            - transform-core-aio-2
        volumes:
            - ./config/nginx-core-aio.conf:/etc/nginx/nginx.conf

    shared-file-store-1:
        image: quay.io/alfresco/alfresco-shared-file-store:0.16.0
        mem_limit: 512m
        environment:
            JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
            scheduler.content.age.millis: 86400000
            scheduler.cleanup.interval: 86400000
        volumes:
            - shared-file-store-volume:/tmp/Alfresco/sfs

    shared-file-store-2:
        image: quay.io/alfresco/alfresco-shared-file-store:0.16.0
        mem_limit: 512m
        environment:
            JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
            scheduler.content.age.millis: 86400000
            scheduler.cleanup.interval: 86400000
        volumes:
            - shared-file-store-volume:/tmp/Alfresco/sfs

    shared-file-store-proxy:
        image: nginx:stable-alpine
        depends_on:
            - shared-file-store-1
            - shared-file-store-2
        volumes:
            - ./config/nginx-shared-file-store.conf:/etc/nginx/nginx.conf

    share:
        image: quay.io/alfresco/alfresco-share:7.1.0.1
        mem_limit: 1g
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            JAVA_OPTS: "
                -XX:MinRAMPercentage=50
                -XX:MaxRAMPercentage=80
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "

    postgres:
        image: postgres:13.1
        mem_limit: 512m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432

    solr6:
        image: alfresco/alfresco-search-services:2.0.2
        mem_limit: 2g
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
            #HTTP by default
            - ALFRESCO_SECURE_COMMS=none
        ports:
            - 8083:8983 #Browser port

    activemq:
        image: alfresco/alfresco-activemq:5.16.1
        mem_limit: 1g
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP

    digital-workspace:
        image: quay.io/alfresco/alfresco-digital-workspace:2.4.2-adw
        mem_limit: 128m
        environment:
            APP_CONFIG_AUTH_TYPE: "BASIC"
            BASE_PATH: ./

    proxy:
        image: alfresco/alfresco-acs-nginx:3.1.1
        mem_limit: 128m
        environment:
            DISABLE_SYNCSERVICE: "true"
        depends_on:
            - alfresco
            - digital-workspace
        ports:
            - 8080:8080
        links:
            - digital-workspace
            - alfresco
            - share

# Shared volume for every shared-file-store service
volumes:
    shared-file-store-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs
